### ISSUE TITLE
Traefik rules for pi-hole

### ISSUE THREAD

**Issue by jimklonowski** [anandslab/deployarr#26]
In your smarthomebeginner guides from a few years back you had set up some Traefik rules for reverse-proxying the pihole admin panel.  Will you be adding something like this to deployarr?  Or alternatively an adguard option

```
http:
  routers:
    pihole-rtr:
      rule: "Host(`pihole.{{env "DOMAINNAME"}}`)"
      entrypoints:
        - https
      middlewares:
        - chain-no-auth
        - pihole-redirectregex
        - pihole-add-admin
      service: pihole-svc
      tls:
        certResolver: dns-cloudflare
  middlewares:
    pihole-add-admin:
      addPrefix:
        prefix: "/admin"
    pihole-redirectregex:
      redirectRegex:
        regex: /admin/$
        replacement: /
  services:
    pihole-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.10.88:80"
```
